### ISSUE TITLE
Hive custom component no longer functions.

### ISSUE THREAD

**Issue by wiredworm** [Pyhass/Hive-Custom-Component#124]
**Describe the bug**
I had been using the component for some time with no problems but recently i'd noticed that it had failed to work.  I've uninstalled then readded the component but the problem persists.  I've also verified that 2FA is not enabled on my account, that the credentials are right and that my Hive App still works as expected.  All of that checks out.

**To Reproduce**
Steps to reproduce the behaviour:

1. Simply reboot the instance of Home Assistant and then check the logs.  I've included a sample of the error i'm seeing below.

**Expected behaviour**
Previously I was seeing data from the various Hive devices I have.  Now they all report as unavailable.

**Screenshots**
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hive/__init__.py", line 89, in async_setup_entry
    devices = await hive.session.startSession(hive_config)
  File "/usr/local/lib/python3.10/site-packages/apyhiveapi/session.py", line 494, in startSession
    await self.getDevices("No_ID")
  File "/usr/local/lib/python3.10/site-packages/apyhiveapi/session.py", line 417, in getDevices
    await self.hiveRefreshTokens()
  File "/usr/local/lib/python3.10/site-packages/apyhiveapi/session.py", line 304, in hiveRefreshTokens
    result = await self.auth.refresh_token(
  File "/usr/local/lib/python3.10/site-packages/apyhiveapi/api/hive_auth_async.py", line 548, in refresh_token
    result = await self.loop.run_in_executor(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 691, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 739, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/usr/local/lib/python3.10/site-packages/botocore/validate.py", line 360, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter AuthParameters, value: ({'REFRESH_TOKEN': 'REDACTED'},), type: <class 'tuple'>, valid types: <class 'dict'>`

**Desktop (please complete the following information):**

- MacOS
- Firefox 
- 102.0.1

**Additional context**

**Comment by KJonline** [comment]
@wiredworm  hive have recently inforced 2FA on their hive app so when the integration upgraded to the new auth system it is now mandatory to have 2fa on to use this integration
