### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by perjury** [Pyhass/Hive-Custom-Component#138]
**Describe the bug**
Hive integration failing to initialise

**To Reproduce**
Eveything had been working fine. Woke up to find Hive component was not working. Tried reloading. No good.
So deleted component, restarted HA and tried to re-add the configuration

Passes 2FA OK but then fails to initialise with this error log:

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/hive/__init__.py:89
Integration: Hive
First occurred: 07:23:36 (1 occurrences)
Last logged: 07:23:36

Error setting up entry p#######t@gmail.com for hive
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hive/__init__.py", line 89, in async_setup_entry
    devices = await hive.session.startSession(hive_config)
  File "/usr/local/lib/python3.10/site-packages/apyhiveapi/session.py", line 503, in startSession
    await self.getDevices("No_ID")
  File "/usr/local/lib/python3.10/site-packages/apyhiveapi/session.py", line 427, in getDevices
    api_resp_d = await self.api.getAll()
  File "/usr/local/lib/python3.10/site-packages/apyhiveapi/api/hive_async_api.py", line 147, in getAll
    json_return.update({"original": resp.status})
AttributeError: 'NoneType' object has no attribute 'status'

Home Assistant 2023.1.5
Supervisor 2022.12.1
Operating System 9.4
Frontend 20230110.0 - latest

Update:
Went back to overnight backup and this is log for Hive prior to deleting and reinstalling

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/hive/__init__.py:89
Integration: Hive
First occurred: 08:05:52 (1 occurrences)
Last logged: 08:05:52

Error setting up entry .....@gmail.com for hive
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hive/__init__.py", line 89, in async_setup_entry
    devices = await hive.session.startSession(hive_config)
  File "/usr/local/lib/python3.10/site-packages/apyhiveapi/session.py", line 503, in startSession
    await self.getDevices("No_ID")
  File "/usr/local/lib/python3.10/site-packages/apyhiveapi/session.py", line 427, in getDevices
    api_resp_d = await self.api.getAll()
  File "/usr/local/lib/python3.10/site-packages/apyhiveapi/api/hive_async_api.py", line 147, in getAll
    json_return.update({"original": resp.status})
AttributeError: 'NoneType' object has no attribute 'status'

**Comment by orangelizard** [comment]
Same here, although other non home assistant related internet based issues for me and other colleagues so possible related to a larger problem.

**Comment by jules51x** [comment]
Reporting the same here. Lost connection around 4am (GMT). Integration now states 'Failed to set up. Check the logs' following a HA reboot. I suspect something on the HIVE end.

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/hive/__init__.py:89
Integration: Hive
First occurred: 08:35:23 (1 occurrences)
Last logged: 08:35:23

Error setting up entry jules51@mac.com for hive
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 372, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hive/__init__.py", line 89, in async_setup_entry
    devices = await hive.session.startSession(hive_config)
  File "/usr/local/lib/python3.10/site-packages/apyhiveapi/session.py", line 503, in startSession
    await self.getDevices("No_ID")
  File "/usr/local/lib/python3.10/site-packages/apyhiveapi/session.py", line 427, in getDevices
    api_resp_d = await self.api.getAll()
  File "/usr/local/lib/python3.10/site-packages/apyhiveapi/api/hive_async_api.py", line 147, in getAll
    json_return.update({"original": resp.status})
AttributeError: 'NoneType' object has no attribute 'status'

Home Assistant 2022.12.1
Supervisor 2022.12.1
Operating System 9.0
Frontend 20221208.0 - latest

**Comment by keviny1273** [comment]
I don’t think I am getting the same errors but my Hive mobile app is not working. HA stopped updating at 4:20am this morning. I’m assuming there is a Hive issue - but their status page is not showing anything - not that it ever does.

**Comment by perjury** [comment]
This just appeared on the Hive twitter account:

We are aware of an issue affecting customers use of their app. Our engineers are currently working to fix this. Please keep an eye on our status page. We are sorry for any inconvenience.

So I guess the issue is at their end :-)

**Comment by adamburgoyne** [comment]
Hive have been increasingly unreliable recently, I think this is their second large outage in 2 months now... Their status page does tend to lag behind a bit but it's always good to check on downdetector before posting a github issue, there were a few reports this morning there of auth issues before Hive themselves realised (I suspect their internal monitoring is a bit subpar).

**Comment by perjury** [comment]
Yeah, I should have checked Hive first. I'll close this issue.
