### ISSUE TITLE
[BUG] All devices and entities offline / not loading

### ISSUE THREAD

**Issue by Paddington1970** [Pyhass/Hive-Custom-Component#90]
**Describe the bug**
I’ve been using the Hive custom integration (installed via HACS) for the past couple of months, but towards the end of last week all my Hive devices and entities suddenly went offline. I can’t get them back online.

**To Reproduce**
Steps to reproduce the behaviour:

1. I’m running hassos (core-2021.4.6 and Home Assistant OS 5.13) on a Rasberry Pi 4.
2. I’ve since tried uninstalling and reinstalling both the custom and also the new core integration, and even tried a clean re-install of hassos, but with joy.
3. I can successfully log in to my Hive account with the custom component (both with 2FA enabled and disabled in my Hive account) but no devices and entities then load, even though the Hive integration card shows amongst my loaded integrations.

**Expected behaviour**
Log into Hive and access to its devices.

**Screenshots**
No screenshot but here’s my log entry showing the error message on startup:

Logger: homeassistant.config_entries
Source: custom_components/hive/__init__.py:76 
First occurred: 21:07:58 (1 occurrences) 
Last logged: 21:07:58
Error setting up entry XXXX@XX.com for hive
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 249, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/hive/__init__.py", line 76, in async_setup_entry
    devices = await hive.session.startSession(hive_config)
  File "/usr/local/lib/python3.8/site-packages/apyhiveapi/session.py", line 271, in startSession
    return await self.createDevices()
  File "/usr/local/lib/python3.8/site-packages/apyhiveapi/session.py", line 289, in createDevices
    eval("self." + code)
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/apyhiveapi/session.py", line 84, in addList
    device = self.helper.getDeviceData(data)
  File "/usr/local/lib/python3.8/site-packages/apyhiveapi/helper/hive_helper.py", line 68, in getDeviceData
    device = self.session.data.devices[product["props"]["trvs"][0]]
IndexError: list index out of range

**Desktop (please complete the following information):**

- OS: iOS
- Browser: Mainly the Home Assistant app (but the same issue occurs when accessing via all installed browsers).

**Additional context**

**Comment by Paddington1970** [comment]
My problem has now resolved. One of my TRVs had been frequently going offline and so I’d been uninstalling and re-installing it. When I checked my Hive app today, I noticed that I had a ‘ghost’ offline duplicate TRV showing amongst its devices. I contacted Hive support and after some false attempts they were able to remove this offline/duplicate device for me. All my other Hive devices immediately then re-loaded when I reinstalled the Home Assistant integration. So I think my problem lay at the Hive end of things.
